@startuml
skinparam sequence {
    MessageAlign center
}
title DSS pour un scénario adapté de <i>Jouer aux dés</i>\n(3 dés, gagné si somme ≤ 10)
actor ":Joueur" as c
participant ":Système" as s

c -> s : démarrerJeu(nom : String)

loop pas terminé
    c -> s : jouer(nom : String)
    s --> c : nom, v1, v2, v3, somme,\nrésultat (gagné si somme ≤ 10),\nnb de parties, nb de parties gagnées
end loop

c -> s : terminerJeu(nom : String)
@enduml