@startuml
left to right direction


class "Joueur"
class "APIJeu" <<boundary>>
class "ControleurJeu" <<control>> {
  +redemarrerJeu(): void
}
class ":JeuDeDes" {
  joueurs: Map<String, Joueur>
  nbTours: int
  +redemarrerJeu(): void
}

"Joueur" --> "APIJeu" : GET /jeu/redemarrerJeu
"APIJeu" --> "ControleurJeu" : redemarrerJeu()
"ControleurJeu" --> ":JeuDeDes" : redemarrerJeu()

@enduml
