@startuml
title RDCU pour jouer (3 dés, gagné si somme ≤ 10)

participant ":JeuDeDes" as c
participant "joueurs:\nMap<String,Joueur>" as jm
participant "d1:De" as d1
participant "d2:De" as d2
participant "d3:De" as d3
participant "j:Joueur" as j

->c : jouer(nom)
c->jm : j = chercher(nom)
c->d1 : brasser()
c->d1 : v1 = valeur
c->d2 : brasser()
c->d2 : v2 = valeur
c->d3 : brasser()
c->d3 : v3 = valeur
c->j : incNbParties()
opt v1 + v2 + v3 <= 10
  c->j : incNbPartiesGagnees()
end opt
c->j : p = nbParties
c->j : g = nbPartiesGagnees
@enduml
